apiVersion: apps/v1
kind: Deployment
metadata:
  name: Movie-Rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Movie-Rating
  template:
    metadata:
      labels:
        app: Movie-Rating
    spec:
      containers:
      - name: Movie-Rating
        image: chinnasamy23mis0481/Movie-Rating:latest
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: Movie-Rating-service
spec:
  type: NodePort
  selector:
    app: Movie-Rating
  ports:
  - port: 81
    targetPort: 81
    nodePort: 30012